---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
data:
  AMQP_BROKER_URL: >-
    failover:(amqp://BROKER_URL,amqp://BROKER_URL)?jms.username=${AMQ_CLUSTER_USER}&jms.password=${AMQ_CLUSTER_PASSWORD}
  AMQ_CLUSTER_PASSWORD: NfZAjak6
  AMQ_CLUSTER_USER: W6nrZd6L
  BROKER_URL: 'tcp://BROKER_URL'
  LOG_LEVEL: INFO
  QUEUE: amqp-address::amqp-queue
  OPENWIRE_QUEUE: openwire-address::openwire-queue
  OPENWIRE_BROKER_URL: >-
    failover:(tcp://BROKER_URL,tcp://BROKER_URL)?jms.username=${AMQ_CLUSTER_USER}&jms.password=${AMQ_CLUSTER_PASSWORD}

